default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: quadros

test:
  <<: *default
  database: quadros_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
